/**
 * @file utest_ipmi_fru_parser.cpp
 *
 * Unit tests for IpmiFruParser.
 *
 * Binary fixtures are generated by gen_ipmi_fru_fixtures.py and stored in
 * test/vpd_files/.  All checksums in those files are correct per the IPMI
 * Platform Management FRU Information Storage Definition v1.0 Rev 1.3 spec.
 *
 * Test categories:
 *   1. Common Header validation (version, checksum, size)
 *   2. Product Info Area parsing (8-bit ASCII fields, empty field)
 *   3. Board Info Area parsing (timestamp, all fields, custom fields)
 *   4. Chassis Info Area parsing (type byte, predefined + custom fields)
 *   5. MultiRecord Area parsing (type ID, data bytes, multi-record chaining)
 *   6. All-areas image (Internal + Chassis + Board + Product + MultiRecord)
 *   7. 6-bit packed ASCII decoding
 *   8. Bad checksum rejection (header, board area, product area, multirecord
 * hdr)
 *   9. Structural errors (truncated buffer, field length overflow)
 *  10. readKeywordFromHardware (hit, miss, wrong param type)
 *  11. writeKeywordOnHardware (in-memory update + checksum recalc, clamping,
 *                              no-file-path error, no-open-stream error,
 *                              empty keyword/value errors)
 *  12. Empty input vector
 */

#include "exceptions.hpp"
#include "ipmi_fru_parser.hpp"
#include "types.hpp"

#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <numeric>

#include <gtest/gtest.h>

using namespace vpd;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Read an entire binary file into a BinaryVector. */
static types::BinaryVector readFile(const std::string& i_path)
{
    std::ifstream l_f(i_path, std::ios::binary);
    if (!l_f.is_open())
    {
        throw std::runtime_error("Cannot open fixture: " + i_path);
    }
    return types::BinaryVector(std::istreambuf_iterator<char>(l_f),
                               std::istreambuf_iterator<char>());
}

/** Extract a BinaryVector from the parsed KeywordVpdMap. Asserts the key
 * exists. */
static types::BinaryVector getVec(const types::KeywordVpdMap& i_map,
                                  const std::string& i_key)
{
    auto l_it = i_map.find(i_key);
    if (l_it == i_map.end())
    {
        ADD_FAILURE() << "Key not found in parsed map: " << i_key;
        return {};
    }
    if (auto* l_v = std::get_if<types::BinaryVector>(&l_it->second))
    {
        return *l_v;
    }
    ADD_FAILURE() << "Value for key '" << i_key << "' is not a BinaryVector";
    return {};
}

/** Convert a BinaryVector to its string representation. */
static std::string vecToStr(const types::BinaryVector& i_vec)
{
    return std::string(i_vec.begin(), i_vec.end());
}

/** Recompute zero-sum checksum over [data[0] .. data[n-2]] and return it. */
[[maybe_unused]] static uint8_t computeChecksum(
    const types::BinaryVector& i_data, size_t i_start, size_t i_onePastLast)
{
    uint8_t l_sum = 0;
    for (size_t i = i_start; i < i_onePastLast; ++i)
    {
        l_sum = static_cast<uint8_t>(l_sum + i_data[i]);
    }
    return static_cast<uint8_t>(~l_sum + 1);
}

// ---------------------------------------------------------------------------
// Suite 1: Common Header validation
// ---------------------------------------------------------------------------

/** Parsing a buffer smaller than 8 bytes must throw DataException. */
TEST(IpmiFruParserHdr, TruncatedBufferThrows)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_truncated.dat");
    IpmiFruParser l_parser(l_vec);
    EXPECT_THROW(l_parser.parse(), DataException);
}

/** Empty input vector must throw DataException. */
TEST(IpmiFruParserHdr, EmptyVectorThrows)
{
    IpmiFruParser l_parser(types::BinaryVector{});
    EXPECT_THROW(l_parser.parse(), DataException);
}

/** Corrupted Common Header checksum must throw DataException. */
TEST(IpmiFruParserHdr, BadHeaderChecksumThrows)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_bad_hdr_checksum.dat");
    IpmiFruParser l_parser(l_vec);
    EXPECT_THROW(l_parser.parse(), DataException);
}

/** Wrong format version in Common Header byte[0] must throw DataException. */
TEST(IpmiFruParserHdr, BadFormatVersionThrows)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_bad_format_version.dat");
    IpmiFruParser l_parser(l_vec);
    EXPECT_THROW(l_parser.parse(), DataException);
}

/** Valid 8-byte header with no areas returns an empty KeywordVpdMap. */
TEST(IpmiFruParserHdr, HeaderOnlyNoAreasReturnsEmptyMap)
{
    // Build a minimal valid 8-byte header with all area offsets = 0.
    types::BinaryVector l_hdr = {0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    uint8_t l_cs = static_cast<uint8_t>(
        ~std::accumulate(l_hdr.begin(), l_hdr.end(), uint8_t{0}) + 1);
    l_hdr.push_back(l_cs);

    IpmiFruParser l_parser(l_hdr);
    auto l_result = l_parser.parse();
    auto* l_map = std::get_if<types::KeywordVpdMap>(&l_result);
    ASSERT_NE(l_map, nullptr);
    EXPECT_TRUE(l_map->empty());
}

// ---------------------------------------------------------------------------
// Suite 2: Product Info Area
// ---------------------------------------------------------------------------

class IpmiFruProductOnly : public ::testing::Test
{
  protected:
    void SetUp() override
    {
        auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
        IpmiFruParser l_parser(std::move(l_vec));
        auto l_variant = l_parser.parse();
        auto* l_ptr = std::get_if<types::KeywordVpdMap>(&l_variant);
        ASSERT_NE(l_ptr, nullptr) << "parse() did not return KeywordVpdMap";
        m_map = *l_ptr;
    }
    types::KeywordVpdMap m_map;
};

TEST_F(IpmiFruProductOnly, ManufacturerDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "PRODUCT_Manufacturer")), "Samsung");
}

TEST_F(IpmiFruProductOnly, ProductNameDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "PRODUCT_ProductName")), "PM9D3a NVMe");
}

TEST_F(IpmiFruProductOnly, PartModelNumberDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "PRODUCT_PartModelNumber")),
              "MZWLR7T6HALA");
}

TEST_F(IpmiFruProductOnly, VersionDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "PRODUCT_Version")), "1.0");
}

TEST_F(IpmiFruProductOnly, SerialNumberDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "PRODUCT_SerialNumber")),
              "S6ERNX0T123456");
}

TEST_F(IpmiFruProductOnly, AssetTagDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "PRODUCT_AssetTag")), "ASSET-001");
}

TEST_F(IpmiFruProductOnly, EmptyFruFileIdPresent)
{
    // FruFileId was empty — key should exist with an empty BinaryVector.
    auto l_it = m_map.find("PRODUCT_FruFileId");
    ASSERT_NE(l_it, m_map.end());
    auto* l_v = std::get_if<types::BinaryVector>(&l_it->second);
    ASSERT_NE(l_v, nullptr);
    EXPECT_TRUE(l_v->empty());
}

TEST_F(IpmiFruProductOnly, LanguageCodePresent)
{
    auto l_code = getVec(m_map, "PRODUCT_LanguageCode");
    ASSERT_EQ(l_code.size(), 1u);
    EXPECT_EQ(l_code[0], 0x00); // English
}

TEST_F(IpmiFruProductOnly, NoBoardOrChassisKeys)
{
    EXPECT_EQ(m_map.find("BOARD_Manufacturer"), m_map.end());
    EXPECT_EQ(m_map.find("CHASSIS_Type"), m_map.end());
}

/** Corrupted Product area checksum must throw. */
TEST(IpmiFruProductArea, BadChecksumThrows)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_bad_product_checksum.dat");
    IpmiFruParser l_parser(l_vec);
    EXPECT_THROW(l_parser.parse(), DataException);
}

// ---------------------------------------------------------------------------
// Suite 3: Board Info Area
// ---------------------------------------------------------------------------

class IpmiFruBoardOnly : public ::testing::Test
{
  protected:
    void SetUp() override
    {
        auto l_vec = readFile("vpd_files/ipmi_fru_board_only.dat");
        IpmiFruParser l_parser(std::move(l_vec));
        auto l_variant = l_parser.parse();
        auto* l_ptr = std::get_if<types::KeywordVpdMap>(&l_variant);
        ASSERT_NE(l_ptr, nullptr);
        m_map = *l_ptr;
    }
    types::KeywordVpdMap m_map;
};

TEST_F(IpmiFruBoardOnly, ManufacturerDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "BOARD_Manufacturer")), "Samsung");
}

TEST_F(IpmiFruBoardOnly, ProductNameDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "BOARD_ProductName")), "PM1753 E3.S");
}

TEST_F(IpmiFruBoardOnly, SerialNumberDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "BOARD_SerialNumber")), "S7A1NX0T654321");
}

TEST_F(IpmiFruBoardOnly, PartNumberDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "BOARD_PartNumber")), "MZWLJ7T6HALA");
}

TEST_F(IpmiFruBoardOnly, MfgDateTimePresent)
{
    // Timestamp was 0x0A4B2C minutes; stored LE → bytes [0x2C, 0x4B, 0x0A]
    auto l_ts = getVec(m_map, "BOARD_MfgDateTime");
    ASSERT_EQ(l_ts.size(), 3u);
    EXPECT_EQ(l_ts[0], 0x2C);
    EXPECT_EQ(l_ts[1], 0x4B);
    EXPECT_EQ(l_ts[2], 0x0A);
}

TEST_F(IpmiFruBoardOnly, LanguageCodePresent)
{
    auto l_code = getVec(m_map, "BOARD_LanguageCode");
    ASSERT_EQ(l_code.size(), 1u);
    EXPECT_EQ(l_code[0], 0x00);
}

/** Corrupted Board area checksum must throw. */
TEST(IpmiFruBoardArea, BadChecksumThrows)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_bad_board_checksum.dat");
    IpmiFruParser l_parser(l_vec);
    EXPECT_THROW(l_parser.parse(), DataException);
}

// ---------------------------------------------------------------------------
// Suite 4: All-areas image
// ---------------------------------------------------------------------------

class IpmiFruAllAreas : public ::testing::Test
{
  protected:
    void SetUp() override
    {
        auto l_vec = readFile("vpd_files/ipmi_fru_all_areas.dat");
        IpmiFruParser l_parser(std::move(l_vec));
        auto l_variant = l_parser.parse();
        auto* l_ptr = std::get_if<types::KeywordVpdMap>(&l_variant);
        ASSERT_NE(l_ptr, nullptr);
        m_map = *l_ptr;
    }
    types::KeywordVpdMap m_map;
};

TEST_F(IpmiFruAllAreas, ChassisTypePresent)
{
    auto l_type = getVec(m_map, "CHASSIS_Type");
    ASSERT_EQ(l_type.size(), 1u);
    EXPECT_EQ(l_type[0], 0x17); // Rack Mount
}

TEST_F(IpmiFruAllAreas, ChassisPartNumberDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "CHASSIS_PartNumber")), "CHASSIS-PN-001");
}

TEST_F(IpmiFruAllAreas, ChassisSerialNumberDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "CHASSIS_SerialNumber")),
              "CHASSIS-SN-001");
}

TEST_F(IpmiFruAllAreas, ChassisCustom1Decoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "CHASSIS_Custom1")), "CustomChassis1");
}

TEST_F(IpmiFruAllAreas, BoardManufacturerDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "BOARD_Manufacturer")), "IBM");
}

TEST_F(IpmiFruAllAreas, BoardCustomFieldsDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "BOARD_Custom1")), "BoardCustom1");
    EXPECT_EQ(vecToStr(getVec(m_map, "BOARD_Custom2")), "BoardCustom2");
}

TEST_F(IpmiFruAllAreas, ProductManufacturerDecoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "PRODUCT_Manufacturer")), "IBM");
}

TEST_F(IpmiFruAllAreas, ProductCustom1Decoded)
{
    EXPECT_EQ(vecToStr(getVec(m_map, "PRODUCT_Custom1")), "ProdCustom1");
}

TEST_F(IpmiFruAllAreas, InternalDataPresent)
{
    // INTERNAL_Data must be present and non-empty.
    auto l_it = m_map.find("INTERNAL_Data");
    ASSERT_NE(l_it, m_map.end());
    auto* l_v = std::get_if<types::BinaryVector>(&l_it->second);
    ASSERT_NE(l_v, nullptr);
    EXPECT_FALSE(l_v->empty());
    // First byte must be 0xDE (from payload b"\xDE\xAD...")
    EXPECT_EQ((*l_v)[0], 0xDE);
}

TEST_F(IpmiFruAllAreas, MultiRecord1TypeId)
{
    auto l_tid = getVec(m_map, "MULTIRECORD_1_TypeId");
    ASSERT_EQ(l_tid.size(), 1u);
    EXPECT_EQ(l_tid[0], 0xC0);
}

TEST_F(IpmiFruAllAreas, MultiRecord1DataBytes)
{
    auto l_data = getVec(m_map, "MULTIRECORD_1");
    ASSERT_EQ(l_data.size(), 4u);
    EXPECT_EQ(l_data[0], 0x01);
    EXPECT_EQ(l_data[1], 0x02);
    EXPECT_EQ(l_data[2], 0x03);
    EXPECT_EQ(l_data[3], 0x04);
}

TEST_F(IpmiFruAllAreas, MultiRecord2DataBytes)
{
    auto l_data = getVec(m_map, "MULTIRECORD_2");
    ASSERT_EQ(l_data.size(), 2u);
    EXPECT_EQ(l_data[0], 0xAB);
    EXPECT_EQ(l_data[1], 0xCD);
}

// ---------------------------------------------------------------------------
// Suite 5: MultiRecord-only image
// ---------------------------------------------------------------------------

TEST(IpmiFruMultiRecord, ThreeRecordsChainingParsed)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_multirecord_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));
    auto l_variant = l_parser.parse();
    auto* l_map = std::get_if<types::KeywordVpdMap>(&l_variant);
    ASSERT_NE(l_map, nullptr);

    // Record 1: typeId=0xC0, data={0x10,0x20,0x30}
    auto l_t1 = getVec(*l_map, "MULTIRECORD_1_TypeId");
    ASSERT_EQ(l_t1.size(), 1u);
    EXPECT_EQ(l_t1[0], 0xC0);
    auto l_d1 = getVec(*l_map, "MULTIRECORD_1");
    ASSERT_EQ(l_d1.size(), 3u);
    EXPECT_EQ(l_d1[0], 0x10);

    // Record 2: typeId=0xC1
    auto l_t2 = getVec(*l_map, "MULTIRECORD_2_TypeId");
    ASSERT_EQ(l_t2.size(), 1u);
    EXPECT_EQ(l_t2[0], 0xC1);

    // Record 3: typeId=0xC2, zero-length data, End-of-list
    auto l_t3 = getVec(*l_map, "MULTIRECORD_3_TypeId");
    ASSERT_EQ(l_t3.size(), 1u);
    EXPECT_EQ(l_t3[0], 0xC2);
    auto l_d3 = getVec(*l_map, "MULTIRECORD_3");
    EXPECT_TRUE(l_d3.empty());

    // No Record 4 should exist.
    EXPECT_EQ(l_map->find("MULTIRECORD_4_TypeId"), l_map->end());
}

/** Corrupted MultiRecord header checksum must throw. */
TEST(IpmiFruMultiRecord, BadHeaderChecksumThrows)
{
    auto l_vec =
        readFile("vpd_files/ipmi_fru_bad_multirecord_hdr_checksum.dat");
    IpmiFruParser l_parser(l_vec);
    EXPECT_THROW(l_parser.parse(), DataException);
}

// ---------------------------------------------------------------------------
// Suite 6: 6-bit ASCII decoding
// ---------------------------------------------------------------------------

TEST(IpmiFru6BitAscii, ManufacturerDecodedCorrectly)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_6bit_ascii.dat");
    IpmiFruParser l_parser(std::move(l_vec));
    auto l_variant = l_parser.parse();
    auto* l_map = std::get_if<types::KeywordVpdMap>(&l_variant);
    ASSERT_NE(l_map, nullptr);

    // "SAMSUNG" was encoded in 6-bit ASCII; must decode back exactly.
    EXPECT_EQ(vecToStr(getVec(*l_map, "BOARD_Manufacturer")), "SAMSUNG");
}

TEST(IpmiFru6BitAscii, ProductNameDecodedCorrectly)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_6bit_ascii.dat");
    IpmiFruParser l_parser(std::move(l_vec));
    auto l_variant = l_parser.parse();
    auto* l_map = std::get_if<types::KeywordVpdMap>(&l_variant);
    ASSERT_NE(l_map, nullptr);

    // "PM9D3A" was encoded in 6-bit ASCII.
    EXPECT_EQ(vecToStr(getVec(*l_map, "BOARD_ProductName")), "PM9D3A");
}

// ---------------------------------------------------------------------------
// Suite 7: Structural error — field length overflow
// ---------------------------------------------------------------------------

/** A field whose declared length exceeds the area boundary must throw. */
TEST(IpmiFruStructural, FieldLengthOverrunThrows)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_field_overrun.dat");
    IpmiFruParser l_parser(l_vec);
    EXPECT_THROW(l_parser.parse(), DataException);
}

// ---------------------------------------------------------------------------
// Suite 8: readKeywordFromHardware
// ---------------------------------------------------------------------------

TEST(IpmiFruReadKw, ExistingKeyReturnsCorrectBytes)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));
    l_parser.parse();

    types::ReadVpdParams l_params = types::Keyword{"PRODUCT_SerialNumber"};
    auto l_result = l_parser.readKeywordFromHardware(l_params);

    auto* l_bv = std::get_if<types::BinaryVector>(&l_result);
    ASSERT_NE(l_bv, nullptr);
    EXPECT_EQ(std::string(l_bv->begin(), l_bv->end()), "S6ERNX0T123456");
}

TEST(IpmiFruReadKw, MissingKeyThrowsInvalidArgument)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));
    l_parser.parse();

    types::ReadVpdParams l_params = types::Keyword{"BOARD_Manufacturer"};
    EXPECT_THROW(l_parser.readKeywordFromHardware(l_params),
                 types::DbusInvalidArgument);
}

TEST(IpmiFruReadKw, EmptyKeyThrowsInvalidArgument)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));
    l_parser.parse();

    types::ReadVpdParams l_params = types::Keyword{""};
    EXPECT_THROW(l_parser.readKeywordFromHardware(l_params),
                 types::DbusInvalidArgument);
}

TEST(IpmiFruReadKw, WrongParamTypeThrowsInvalidArgument)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));
    l_parser.parse();

    // IpzType (Record, Keyword) is wrong for IpmiFruParser
    types::ReadVpdParams l_params = types::IpzType{"VINI", "SN"};
    EXPECT_THROW(l_parser.readKeywordFromHardware(l_params),
                 types::DbusInvalidArgument);
}

TEST(IpmiFruReadKw, TriggersLazyParseWhenNotYetParsed)
{
    // Call readKeywordFromHardware without calling parse() first;
    // the parser should call parse() internally.
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));

    types::ReadVpdParams l_params = types::Keyword{"PRODUCT_Manufacturer"};
    auto l_result = l_parser.readKeywordFromHardware(l_params);
    auto* l_bv = std::get_if<types::BinaryVector>(&l_result);
    ASSERT_NE(l_bv, nullptr);
    EXPECT_EQ(std::string(l_bv->begin(), l_bv->end()), "Samsung");
}

// ---------------------------------------------------------------------------
// Suite 9: writeKeywordOnHardware — error paths (no file)
// ---------------------------------------------------------------------------

TEST(IpmiFruWriteKw, NoFilePathThrowsDataException)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    // Construct without a file path → write must throw
    IpmiFruParser l_parser(std::move(l_vec));
    l_parser.parse();

    types::WriteVpdParams l_params = types::KwData{
        "PRODUCT_SerialNumber", types::BinaryVector{'A', 'B', 'C'}};
    EXPECT_THROW(l_parser.writeKeywordOnHardware(l_params), DataException);
}

TEST(IpmiFruWriteKw, EmptyKeywordThrowsDataException)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));

    types::WriteVpdParams l_params =
        types::KwData{"", types::BinaryVector{'A'}};
    EXPECT_THROW(l_parser.writeKeywordOnHardware(l_params), DataException);
}

TEST(IpmiFruWriteKw, EmptyValueThrowsDataException)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));

    types::WriteVpdParams l_params =
        types::KwData{"PRODUCT_SerialNumber", types::BinaryVector{}};
    EXPECT_THROW(l_parser.writeKeywordOnHardware(l_params), DataException);
}

TEST(IpmiFruWriteKw, WrongParamTypeThrowsInvalidArgument)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));

    // IpzData is the wrong variant for IpmiFruParser
    types::WriteVpdParams l_params =
        types::IpzData{"VINI", "SN", types::BinaryVector{'X'}};
    EXPECT_THROW(l_parser.writeKeywordOnHardware(l_params),
                 types::DbusInvalidArgument);
}

// ---------------------------------------------------------------------------
// Suite 10: writeKeywordOnHardware — successful write with checksum update
// ---------------------------------------------------------------------------

/**
 * Copy the writeable_product fixture to a real tmpfile, open an
 * IpmiFruParser on it, write a new serial number, then re-parse the
 * file from disk and verify the new value and valid area checksum.
 */
TEST(IpmiFruWriteKw, WriteUpdatesFileAndChecksum)
{
    // Step 1 — copy fixture to a temporary file.
    const std::string l_src = "vpd_files/ipmi_fru_writeable_product.dat";
    const std::string l_tmp = std::tmpnam(nullptr); // NOLINT
    {
        std::ifstream l_in(l_src, std::ios::binary);
        ASSERT_TRUE(l_in.is_open()) << "Cannot open " << l_src;
        std::ofstream l_out(l_tmp, std::ios::binary | std::ios::trunc);
        ASSERT_TRUE(l_out.is_open()) << "Cannot create tmpfile " << l_tmp;
        l_out << l_in.rdbuf();
    }

    // Step 2 — parse and write new serial number.
    {
        auto l_vec = readFile(l_tmp);
        IpmiFruParser l_parser(std::move(l_vec), l_tmp);
        l_parser.parse();

        const std::string l_newSerial = "NEWSERIAL001";
        types::WriteVpdParams l_params = types::KwData{
            "PRODUCT_SerialNumber",
            types::BinaryVector(l_newSerial.begin(), l_newSerial.end())};
        int l_written = l_parser.writeKeywordOnHardware(l_params);
        EXPECT_EQ(l_written, static_cast<int>(l_newSerial.size()));
    }

    // Step 3 — re-read the file from disk and re-parse.
    auto l_updated = readFile(l_tmp);
    IpmiFruParser l_parser2(l_updated);
    auto l_variant = l_parser2.parse();
    auto* l_map = std::get_if<types::KeywordVpdMap>(&l_variant);
    ASSERT_NE(l_map, nullptr);

    // Step 4 — verify serial number value was updated.
    EXPECT_EQ(vecToStr(getVec(*l_map, "PRODUCT_SerialNumber")), "NEWSERIAL001");

    // Step 5 — verify the product area checksum is still valid in the file.
    const size_t l_prodOffset =
        l_updated[4] * 8u; // byte[4] = product offset units
    const size_t l_prodLen = l_updated[l_prodOffset + 1] * 8u;
    uint8_t l_sum = 0;
    for (size_t i = l_prodOffset; i < l_prodOffset + l_prodLen; ++i)
    {
        l_sum = static_cast<uint8_t>(l_sum + l_updated[i]);
    }
    EXPECT_EQ(l_sum, 0u) << "Product area checksum is invalid after write";

    std::remove(l_tmp.c_str());
}

/**
 * If the new value is shorter than the field capacity, only the written
 * bytes are changed; the remainder of the field in memory keeps the old bytes.
 * The count returned must equal the length of the new value, not the capacity.
 */
TEST(IpmiFruWriteKw, WriteClampedToCapacity)
{
    const std::string l_src = "vpd_files/ipmi_fru_writeable_product.dat";
    const std::string l_tmp = std::tmpnam(nullptr); // NOLINT
    {
        std::ifstream l_in(l_src, std::ios::binary);
        ASSERT_TRUE(l_in.is_open());
        std::ofstream l_out(l_tmp, std::ios::binary | std::ios::trunc);
        l_out << l_in.rdbuf();
    }

    auto l_vec = readFile(l_tmp);
    IpmiFruParser l_parser(std::move(l_vec), l_tmp);
    l_parser.parse();

    // Write only 5 bytes into a 12-byte serial number field.
    const std::string l_shortSN = "SHORT";
    types::WriteVpdParams l_params =
        types::KwData{"PRODUCT_SerialNumber",
                      types::BinaryVector(l_shortSN.begin(), l_shortSN.end())};
    int l_written = l_parser.writeKeywordOnHardware(l_params);
    EXPECT_EQ(l_written, 5);

    std::remove(l_tmp.c_str());
}

/**
 * Writing more bytes than the field capacity: the write must be silently
 * clamped to the field capacity and return that clamped count.
 */
TEST(IpmiFruWriteKw, WriteExceedingCapacityIsClamped)
{
    const std::string l_src = "vpd_files/ipmi_fru_writeable_product.dat";
    const std::string l_tmp = std::tmpnam(nullptr); // NOLINT
    {
        std::ifstream l_in(l_src, std::ios::binary);
        ASSERT_TRUE(l_in.is_open());
        std::ofstream l_out(l_tmp, std::ios::binary | std::ios::trunc);
        l_out << l_in.rdbuf();
    }

    auto l_vec = readFile(l_tmp);
    IpmiFruParser l_parser(std::move(l_vec), l_tmp);
    l_parser.parse();

    // Serial field capacity is 12 bytes; try to write 20.
    types::BinaryVector l_longVal(20, 'Z');
    types::WriteVpdParams l_params =
        types::KwData{"PRODUCT_SerialNumber", l_longVal};
    int l_written = l_parser.writeKeywordOnHardware(l_params);
    EXPECT_EQ(l_written, 12);

    std::remove(l_tmp.c_str());
}

/**
 * Writing to a keyword that does not exist in the parsed map must throw.
 */
TEST(IpmiFruWriteKw, UnknownKeywordThrowsDataException)
{
    const std::string l_src = "vpd_files/ipmi_fru_writeable_product.dat";
    const std::string l_tmp = std::tmpnam(nullptr); // NOLINT
    {
        std::ifstream l_in(l_src, std::ios::binary);
        ASSERT_TRUE(l_in.is_open());
        std::ofstream l_out(l_tmp, std::ios::binary | std::ios::trunc);
        l_out << l_in.rdbuf();
    }

    auto l_vec = readFile(l_tmp);
    IpmiFruParser l_parser(std::move(l_vec), l_tmp);
    l_parser.parse();

    types::WriteVpdParams l_params =
        types::KwData{"BOARD_Manufacturer", types::BinaryVector{'I', 'B', 'M'}};
    EXPECT_THROW(l_parser.writeKeywordOnHardware(l_params), DataException);

    std::remove(l_tmp.c_str());
}

// ---------------------------------------------------------------------------
// Suite 11: parse() return type variant
// ---------------------------------------------------------------------------

/** The VPDMapVariant returned must hold KeywordVpdMap, not monostate or
 * IPZVpdMap. */
TEST(IpmiFruReturnType, VariantHoldsKeywordVpdMap)
{
    auto l_vec = readFile("vpd_files/ipmi_fru_product_only.dat");
    IpmiFruParser l_parser(std::move(l_vec));
    auto l_variant = l_parser.parse();

    EXPECT_FALSE(std::holds_alternative<std::monostate>(l_variant));
    EXPECT_FALSE(std::holds_alternative<types::IPZVpdMap>(l_variant));
    EXPECT_TRUE(std::holds_alternative<types::KeywordVpdMap>(l_variant));
}
